### ISSUE TITLE
Add well signposted link to poplus google group on get involved page

### ISSUE THREAD

**Issue by JenMysoc** [poplus/home-poplus#97]
The get involved page (http://poplus.org/get-involved/) doesn't have a easy link to the Poplus google group which is one of the first things we tell people to join to get involved with Poplus.

**Comment by jpmckinney** [comment]
The words "Poplus online group." and "Join us!" link to the group?

**Comment by paullenz** [comment]
Following up on this (+ with some input from Tom S) - I think that we need to give this a bit of a design scrub.  As Jen rightly says we currently have no obvious link to the Google group under get involved - the first thing is  - Join A Committee.

I will add to our design list for next week, but I think that it should roughly be:
- Join the Google group to hear what is going on and join the world-wide Poplus Community (link) (but with better wording).  Have this at the top of the page with much smaller pic and the first thing on the LHS nav
- Where to find Poplus people (with a bit of added text above the map)
- Find out which events Poplus members are going to be attending so that you can arrange to speak to them face to face (then have a simple list of hand-maintained future events
- then have the write code etc call to action

TBH I would remove the committee link from the nav and this page - still mention that and the minutes etc on the about page

**Comment by jpmckinney** [comment]
Yes, I feel we can scrap a lot of content across poplus.org, which is often more about us figuring out what Poplus should be rather than about concisely communicating what Poplus is. When people hear about Poplus they often want to find the components, and that's rather buried right now. See #83

We should also eliminate all text about Poplus being in its infancy, etc. It doesn't inspire confidence. People want to join something that has legs.

**Comment by wrightmartin** [comment]
Here's a design change to address this...

![screen shot 2014-11-03 at 15 05 47](https://cloud.githubusercontent.com/assets/2292925/4884349/f162505c-636a-11e4-922a-96f0fc6df196.png)

**Comment by jpmckinney** [comment]
+1 I still think having giant photos push the content below the fold is undesirable.

**Comment by paullenz** [comment]
+1

I would also lose committees and meetings / agendas from this page all
together TBH and have on the about page - the priority for getting involved
is joining the community and starting to play around with components

**Comment by wrightmartin** [comment]
@paullenz that makes sense, I'll open a ticket to rearrange some of the content.

**Comment by paullenz** [comment]
Thanks!

**Comment by MyfanwyNixon** [comment]
Just to say that we've rewritten a number of pages, with the following aims:
To remove the mention of committees
To minimise mentions of interoperability
To encourage joining the Google Group as the primary call to action
To explain how you’d go about using a Component
Remove mentions (and intimations) of us being a new organisation

Changes can be seen on this document: https://docs.google.com/a/mysociety.org/document/d/1PYHl6Qsq7KpjDwDv3GSUwaxC5g34qcTf1JfG5q3pG_Y/edit#

and they are being slotted into the next design sprint, I believe. Comments and modifications to the copy are still welcome.

**Comment by MyfanwyNixon** [comment]
And I should explicitly mention that there are a couple of pages which need input from a developer - 
How to use Components https://docs.google.com/a/mysociety.org/document/d/1FkIzDx0C9__yuCs_FH0GnpeP6KeWfyh3eAHmpGcfn5I/edit
and 'Wjat is a Component' http://poplus.org/components/definition/ which I haven't touched because as I mention on the master doc:
"This is the crowd-sourced definition which does contain reference to interoperability. It also says “If you’d like to debate it or improve it, please join the mailing list and tell us what should be different in the next version.” - so we could do that before we start modifying it? The other option would be to soften the language, or add an introductory paragraph to say that Components ‘aspire to’ these qualities but may in practice  only fulfil 5 or 6 of them."
